import './index.html'
import './index.scss'
import catalogPage from './components/catalog-page/catalog.html'
import quizPage from './components/quiz-page/quiz.html'
import resultsPage from './components/results-page/results.html'
import startPage from './components/start-page/start.html'
import songsData from './assets/songs-data/songs.js'
